# Generated by Django 3.2.6 on 2021-08-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, default=0)),
                ('plate', models.CharField(blank=True, max_length=128)),
                ('vehicle_id_number', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('vehicle_model_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='nextlua.vehiclemodel')),
            ],
        ),
    ]
