# Generated by Django 3.2.6 on 2021-08-03 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextlua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name_plural': 'Vehicles'},
        ),
    ]
