# Generated by Django 3.2.6 on 2021-08-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextlua', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
