# Generated by Django 3.2.6 on 2021-08-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextlua', '0003_auto_20210804_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='nextlua.vehiclemodel'),
        ),
    ]
