# Generated by Django 3.2.6 on 2021-08-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextlua', '0004_alter_vehicle_vehicle_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
